version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  docker-linting:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Hadolint
          command: docker run --rm -i ghcr.io/hadolint/hadolint < app/Dockerfile

  docker-build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t capstone ./app
      - run:
          name: tag the image
          command: docker tag capstone $DOCKER_USERNAME/capstone:latest
      - run:
          name: sign in dockerhub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push image
          command: docker push $DOCKER_USERNAME/capstone:latest

  deploy:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install tools
          command: |
            sudo apt install -y tar gzip curl
      - kubernetes/install-kubectl
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: capstone-eks
          aws-region: us-east-1
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ./kubernetes/deployment.yml
          resource-name: deployment/capstone-app
          get-rollout-status: true
          show-kubectl-command: true
      - run:
          name: Test cluster
          command: |
            kubectl get nodes
            kubectl get deployment
            kubectl get pod -o wide
            kubectl get services
      - run:
          name: Cleaning up
          command: docker system prune

workflows:
  capstone-pipeline:
    jobs:
      - docker-linting
      - docker-build:
          requires: [docker-linting]
      - deploy:
          requires: [docker-build]
